### ISSUE TITLE
Warning: Trying to access array offset on value of type null in commerce_product_match_products()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/commerce#10]
![2024-10-17 11 08 19 bd3 lndo site ef2684ec295b](https://github.com/user-attachments/assets/cbc61c77-2a0f-4393-992b-2af48318bc93)

I'm still getting product suggestions when I do this, so I'm not sure if something is broken or not. It's being called from `commerce_product_autocomplete()` which is passed a field_name of `line_item_product_selector`. That field doesn't exist but perhaps it doesn't need to be. The autocomplete path is in `commerce_product_line_item_add_form()` which passes that fake field name.

That same line looks the same in Drupal 7 Commerce 1.x:

```
$cid = implode(':', array(
    $field['field_name'],
    $match,
    ($string !== '' ? $string : implode('-', $ids)),
    $limit,
  ));
```

and I don't see any bug issue for that so I'm still not sure if something is broken or not.

**Comment by herbdool** [comment]
I've confirmed it's the same in D7. The `$field` is NULL so calling `$field['field_name']` should not happen. I was testing on a fresh D7 site with PHP 7.4 so maybe 7.4 ignores that.

**Comment by herbdool** [comment]
@elisseck I've added a PR for this one.

**Comment by elisseck** [comment]
Thank you! I think this looks good, and resolves the warning we know about. I am a little concerned that there could be an issue where two of the same `$results[$cid]` could overwrite eachother... but it doesn't happen with regular product reference fields because they are properly using `$field`.

I'm not sure if it's intended that multiple `line item manager` widgets could ever be used on one form, and it certainly doesn't work now for other reasons... so i'm not going to overthink it right now.
