### ISSUE TITLE
Get automated tests working

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/commerce#27]
In porting complex modules (like OG, which I helped port), I have found that porting tests sooner rather than later is highly beneficial, as you'll find bugs you have missed.

**Comment by elisseck** [comment]
Definitely agreed! This is my current priority.

Tests are mostly running (manually) at this time, and I'm working on the few exceptions that seem to stop backdrop in its tracks that didn't stop d7 tests from completing their run. Not 100% sure what changed there yet but here we are.

There are quite a few failures to take a look at if you're motivated to run them yourself, but I will have time to get to them next week. 90% of them are in "checkout" and I think it might be a problem with the way the tests were written versus what backdrop is doing now, but i'm not 100% sure about this either without diving in.

I'm planning to wait to set up github actions to run the tests automatically until we're at a baseline state of "tests are passing", because just having every PR fail a bunch of tests unrelated to their changes is, imho, super obnoxious.

**Comment by argiepiano** [comment]
Sounds good. Does the current dev version contain the latest versions of the tests you've been tweaking? I may take a look at some point this week.

**Comment by elisseck** [comment]
Yes, dev is up to date what i'm currently working with and i'll make an effort this week to keep it pretty up to date as I fix bits and pieces of the tests.

**Comment by elisseck** [comment]
Well, i've done exactly what I said I wouldn't by accident!

Functional tests are running, there are 0 fails, but there are some exceptions right now stopping them from all passing.

I wasn't getting any exceptions on my local, so there is at least one test there I need to look further into. Most of these are related to `entity_tokens` module and I had forgotten that I doctored my module during this process... I will go PR those changes and I think many of these test exceptions will go away.

I ended up commenting out two tests that I just really couldn't figure out, and created an issue to follow up on those because the feature is also actually broken: https://github.com/backdrop-contrib/commerce/issues/29

I also deleted a test related to `hook_help()`. Besides those three, all tests from the d7 version appear to be running!
